### ISSUE TITLE
Creating room without room switch causes error

### ISSUE THREAD

**Issue by kmickeletto** [adey/bangali#41]
When trying to create a room, I save the room without any changes, then edit the room.

When trying to set the occupied timeout to 1800 seconds, but not specifying an active switch, I get an error trying to save.  However hitting save again does save.  I'm not sure how bad this is.

I checked logs for Room manager and the room in the ide and I don't see any errors.

If I create the room and specify a switch or I don't specify a timeout, I don't get the error.

**Comment by adey** [comment]
> When trying to create a room, I save the room without any changes, then edit the room.

that is the right way to do it ... otherwise i have seen issues with using system state when the app room has been created but not saved it.

> When trying to set the occupied timeout to 1800 seconds, but not specifying an active switch, I get an error trying to save. However hitting save again does save. I'm not sure how bad this is.

so i cant recreate this. here are the steps i followed:
1. click new room
2. give the room a name and save
3. click on room name
4. go to occupied settings and enter 1800 for timeout setting
5. click done then save

it saved first time without any error.

are you able to recreate it? if yes please share the steps.
