### ISSUE TITLE
Problems with room announcement settings

### ISSUE THREAD

**Issue by zuhairmahd** [adey/bangali#59]
Here is the issue:
When I create a new room and save it and then open it again and go to announcement settings, then go to spoken announcement settings, pick a speech device: I have EchoSpeaks with several associated Echos as well as a Sonos speaker; then I set the announcement times and volume level, no matter what I do, I get the following error when I tap Done: “Oops! Looks like you need to double-check some inputs.“.  I’ve checked, double and triple checked but can’t seem to work out what’s going on. 

Thanks.

**Comment by adey** [comment]
sorry for the delayed response ... just seeing this. can you please the live logs for what is the error reported when this happens?

**Comment by mneiderer** [comment]
Hi thanks to helplook the car temperature was 18 c before.when the piston work it change it to min.5/3/2020, 8:55:42 AM +54ms+1ms╔Received event [40].test = 1588510542054 with a delay of 0ms+226ms║RunTime Analysis CS > 25ms > PS > 142ms > PE > 59ms > CE+230ms║Runtime (66162 bytes) successfully initialized in 142ms (v0.3.110.20191009) (228ms)+231ms║╔Execution stage started+240ms║║Cancelling statement #70's schedules...+253ms║║Calculating (string) Bearer + (string) 178fbf715019e98446c1defd057033d8a3824bff1de84bbe8488328c6cdb09aa >> (string) Bearer 178fbf715019e98446c1defd057033d8a3824bff1de84bbe8488328c6cdb09aa+257ms║║Sending external web request to: owner-api.teslamotors.com/api/1/vehicles/+638ms║║Executed virtual command httpRequest (381ms)+643ms║║[count:1, response:[[api_version:7, backseat_token:null, backseat_token_updated_at:null, calendar_enabled:true, color:null, display_name:Dark, id:25226067831571971, id_s:25226067831571971, in_service:false, option_codes:AD15,MDL3,PBSB,RENA,BT37,ID3W,RF3G,S3PB,DRLH,DV2W,W39B,APF0,COUS,BC3B,CH07,PC30,FC3P,FG31,GLFR,HL31,HM31,IL31,LTPB,MR31,FM3B,RS3H,SA3P,STCP,SC04,SU3C,T3CA,TW00,TM00,UT3P,WR00,AU3P,APH3,AF00,ZCST,MI00,CDM0, state:online, tokens:[60bcb1417d85a058, d6e2e2c64ebceafb], vehicle_id:14657249, vin:5YJ3E1EB0KF251166]]]+644ms║║Executed virtual command log (2ms)+651ms║║[online]+652ms║║Executed virtual command log (2ms)+661ms║║Comparison (boolean) true is (boolean) false = false (2ms)+663ms║║Cancelling condition #117's schedules...+664ms║║Condition #117 evaluated false (8ms)+665ms║║Cancelling condition #116's schedules...+666ms║║Condition group #116 evaluated false (state changed) (11ms)+670ms║║Cancelling statement #142's schedules...+678ms║║Calculating (string) https://owner-api.teslamotors.com/api/1/vehicles/ + (string) 25226067831571971 >> (string) https://owner-api.teslamotors.com/api/1/vehicles/25226067831571971+680ms║║Calculating (string) https://owner-api.teslamotors.com/api/1/vehicles/25226067831571971 + (string) /data_request/charge_state >> (string) https://owner-api.teslamotors.com/api/1/vehicles/25226067831571971/data_request/charge_state+690ms║║Calculating (string) Bearer + (string) 178fbf715019e98446c1defd057033d8a3824bff1de84bbe8488328c6cdb09aa >> (string) Bearer 178fbf715019e98446c1defd057033d8a3824bff1de84bbe8488328c6cdb09aa+693ms║║Sending external web request to: owner-api.teslamotors.com/api/1/vehicles/25226067831571971/data_request/charge_state+1372ms║║Executed virtual command httpRequest (680ms)+1377ms║║response:battery_heater_on:false, battery_level:50, battery_range:144.42, charge_current_request:48, charge_current_request_max:48, charge_enable_request:true, charge_energy_added:4.82, charge_limit_soc:51, charge_limit_soc_max:100, charge_limit_soc_min:50, charge_limit_soc_std:90, charge_miles_added_ideal:19.5, charge_miles_added_rated:19.5, charge_port_cold_weather_mode:false, charge_port_door_open:true, charge_port_latch:Engaged, charge_rate:0.0, charge_to_max_range:false, charger_actual_current:0, charger_phases:1, charger_pilot_current:48, charger_power:0, charger_voltage:2, charging_state:Complete, conn_charge_cable:SAE, est_battery_range:107.52, fast_charger_brand:<invalid>, fast_charger_present:false, fast_charger_type:ACSingleWireCAN, ideal_battery_range:144.42, managed_charging_active:false, managed_charging_start_time:null, managed_charging_user_canceled:false, max_range_charge_counter:0, minutes_to_full_charge:0, not_enough_power_to_heat:null, scheduled_charging_pending:false, scheduled_charging...[TRUNCATED]+1378ms║║Executed virtual command log (1ms)+1384ms║║4.82+1385ms║║Executed virtual command log (2ms)+1390ms║║50+1391ms║║Executed virtual command log (1ms)+1397ms║║107.52+1398ms║║Executed virtual command log (2ms)+1404ms║║Complete+1404ms║║Executed virtual command log (1ms)+1414ms║║Comparison (boolean) false is (boolean) true = false (1ms)+1415ms║║Condition #201 evaluated false (7ms)+1422ms║║Comparison (boolean) false is (boolean) true = false (1ms)+1424ms║║Condition #202 evaluated false (8ms)+1431ms║║Comparison (boolean) true is (boolean) true = true (1ms)+1433ms║║Cancelling condition #203's schedules...+1434ms║║Condition #203 evaluated true (9ms)+1435ms║║Cancelling condition #200's schedules...+1436ms║║Condition group #200 evaluated true (state changed) (29ms)+1450ms║║Comparison (time) 32143491 is_between (time) 14400000 .. (time) 28800000 = false (10ms)+1451ms║║Condition #204 evaluated false (14ms)+1452ms║║Cancelling condition #188's schedules...+1453ms║║Condition group #188 evaluated false (state changed) (46ms)+1456ms║║Cancelling statement #209's schedules...+1463ms║║Calculating (string) https://owner-api.teslamotors.com/api/1/vehicles/ + (string) 25226067831571971 >> (string) https://owner-api.teslamotors.com/api/1/vehicles/25226067831571971+1466ms║║Calculating (string) https://owner-api.teslamotors.com/api/1/vehicles/25226067831571971 + (string) /command/set_temps?driver_Temp=:25 >> (string) https://owner-api.teslamotors.com/api/1/vehicles/25226067831571971/command/set_temps?driver_Temp=:25+1476ms║║Calculating (string) Bearer + (string) 178fbf715019e98446c1defd057033d8a3824bff1de84bbe8488328c6cdb09aa >> (string) Bearer 178fbf715019e98446c1defd057033d8a3824bff1de84bbe8488328c6cdb09aa+1479ms║║Sending external web request to: owner-api.teslamotors.com/api/1/vehicles/25226067831571971/command/set_temps?driver_Temp=:25+1877ms║║Executed virtual command httpRequest (399ms)+1884ms║╚Execution stage complete. (1653ms)+1885ms╚Event processed successfully (1885ms)
-------- Message d'origine --------De : adey <notifications@github.com> Date : 20-05-01  11 h 24 p.m.  (GMT-05:00) À : adey/bangali <bangali@noreply.github.com> Cc : Subscribed <subscribed@noreply.github.com> Objet : Re: [adey/bangali] Problems with room announcement settings (#59) 
sorry for the delayed response ... just seeing this. can you please the live logs for what is the error reported when this happens?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/adey/bangali/issues/59#issuecomment-622661558",
"url": "https://github.com/adey/bangali/issues/59#issuecomment-622661558",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
